name: Release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add --update --no-cache build-base
            apk add --update --no-cache openjdk17-jdk
            apk add --update --no-cache rust
            apk add --update --no-cache git
            apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python

            # Create and activate a virtual environment
            python3 -m venv venv
            source venv/bin/activate

            # Upgrade pip and setuptools inside the virtual environment
            pip install --no-cache --upgrade pip setuptools

            # Install ocimatic using pip inside the virtual environment
            pip install git+https://github.com/OCIoficial/ocimatic

            # Run ocimatic
            ocimatic run-testplan
            ocimatic gen-expected
            ocimatic archive

            # Deactivate the virtual environment
            deactivate

      - run: mv archive.zip ${{ github.event.repository.name }}.zip

      - name: Publish Release
        uses: ./.github/actions/github-release
        with:
          files: ${{ github.event.repository.name }}.zip
          name: ${{ github.event.repository.name  }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README.md
        run: |
          .github/scripts/ocimatic-version.py >> README.md
          git config user.name ocimatic
          git config user.email ocimatic@github.com
          git add .
          git commit -m "Release"
          git push
